name = input("Whats your name?")
subject = input("Whats your favourate subject?")
score = input("Whats your target score for this subject?")
print ("=" * 30)
print(f"Hi, {name}!")
print(f"My favourate subject is {subject}.")
print(f"My target score for this is {score}.")
print("=" * 30)
print(f"{name}, you can achieve {score} in {subject}! Just do it!")
